"""
    For the first time, when the project is build, TBC external API needs to verify system HOST with GD PASS.
    For that reason, user has to run this script manually and enter GD pass.
    After that, our HOST will become verified for TBC's server, and we'll be just able to continue using
    their API without manually entering GD passes on every request we made.

"""
import os
import requests
from TBC_API.xml_payloads import TBC_ACCOUNT_STATEMENT_PAYLOAD
from datetime import date

cert_path = os.environ.get("CERT_PATH")
key_path = os.environ.get("KEY_PATH")

PASSWORD = os.environ.get("USER_PASSWORD")
USERS = os.environ.get("TBC_DEFAULT_USER")

url, headers, payload = TBC_ACCOUNT_STATEMENT_PAYLOAD.values()
to_date_str = date.today().strftime("%Y-%m-%d")

for USER in USERS:

    print("THE CODE IS VALID FOR 30 SECONDS AFTER ITS GENERATED.")

    GD_PASS = int(
        input(f"ENTER GD PASS GENERATED BY THE DEVICE OWNED BY USER {USER} : ")
    )

    formatted_payload = payload.format(
        USER, PASSWORD,
        GD_PASS, to_date_str, "_IGNORE_", "GEL"
    )

    response = requests.post(
        url, data=formatted_payload, headers=headers,
        cert=(cert_path, key_path), verify=True
    )

